### PR TITLE
Allow video element

### PR DESCRIPTION
**Pull request by rosylilly**
Please allow video element. I need embed screen casts.

### CODE REVIEW

**Comment by r7kamura** [comment]
@rosylilly Thanks for sending pr!

But unfortunately we cannot merge this pr bacause qiita-markdown is based on Qiita and Qiita:Team specs, and Qiita does not allow embedding `video` element for now :weary: :weary: :weary: 

Although it might be OK to allow embedding `video` element in Qiita:Team (`SCRIPTABLE_RULE` is used in Qiita:Team), I think you would like to use it in Qiita, right?

**Comment by rosylilly** [comment]
I would like to use `video` in __Qiita:Team__.

I'll move rules into `SCRIPTABLE_RULE`. Wait a second.

**Comment by r7kamura** [comment]
Ah, that's good :relaxed:

**Comment by rosylilly** [comment]
Thank you!! I :heart:  Qiita :heart_eyes:

**Pull request merged**
