### PR TITLE
Add Docswell to allowing embed script/iframe list

### PR DESCRIPTION
**Pull request by ku-suke**
# What

This is a request to add docswell.com to the list of embed whitelist (JS/iframe).

https://www.docswell.com/

## Rspec test result

```
~
      with HTML embed code for Docswell
        forces async attribute on script
        with scheme
          forces width attribute on iframe
        without scheme
          forces width attribute on iframe
~
Finished in 1.33 seconds (files took 1.81 seconds to load)
526 examples, 0 failures
```

Note: `.rubocop_todo.yml` is not included in this PR.

### CODE REVIEW

**Review by getty104 — APPROVED** [review]
LGTM!
Thanks for your contribution!

**Review by getty104 — CHANGES_REQUESTED** [review]
Sorry after LGTM, I'm getting an error in lint, could you please do a `bundle exec rubocop -a` run?

**Comment by ku-suke** [comment]
Yes, but this error caused without generating `.rubocop_todo.yml`. 
This error will be fixed after `rubocop --auto-gen-config --exclude-limit 99999`.
You can generate before merge, or can I commit the generated file?

**Comment by getty104** [comment]
@ku-suke 
The `bundle exec rake style:auto_correct` command corrects lint errors. Can you try to run the command ?

**Review by getty104 — APPROVED** [review]
Thanks for the fix, LGTM!

**Pull request merged**
