### PR TITLE
Update rouge dependency version to '~> 4.2'

### PR DESCRIPTION
**Pull request by getty104**
Update rouge dependency.

CHANGELOG

https://github.com/rouge-ruby/rouge/blob/master/CHANGELOG.md#version-420-2023-10-25

There is no breaking change.

### CODE REVIEW

**Comment by kimkim0814** [comment]
【memo】
This update is no breaking change.
It seems there are no changes to the minimum version of the dependent packages on update version 4.2.0.

**Comment by kimkim0814** [comment]
@getty104 
Can I ignore the errors in this test?

https://github.com/increments/qiita-markdown/actions/runs/7690101297/job/20953534987?pr=151

**Comment by getty104** [comment]
>Can I ignore the errors in this test?
https://github.com/increments/qiita-markdown/actions/runs/7690101297/job/20953534987?pr=151

@kimkim0814 
I fixed this broken task in https://github.com/increments/qiita-markdown/pull/152 .

**Review by kimkim0814 — DISMISSED** [review]
LGTM!

**Review by ohakutsu — DISMISSED** [review]
LGTM!

**Review by ohakutsu — APPROVED** [review]
LGTM!
Please fix title of this Pull Request!

**Pull request merged**
