### PR TITLE
HTML5 <details> and <summary>

### PR DESCRIPTION
**Pull request by yuku-t**
## What

Support HTML5 `<details>` and `<summary>` in markdown body.

- [\<details\> - HTML | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)

### Using `<details>` in GitHub

```
<details>
 <summary>Summary Goes Here</summary>
 ...this is hidden, collapsable content...
</details>
```

<details>
 <summary>Summary Goes Here</summary>
 ...this is hidden, collapsable content...
</details>

## Why

Allowing them makes markdown expressive. And they are standardized technology.

### CODE REVIEW

**Comment by yuku-t** [comment]
@r7kamura review please 🙏  (I'm wondering whether I should write tests for this pull-request)
@yaotti @takoratta any comments?

**Comment by r7kamura** [comment]
@yuku-t What do you think about that some browsers like Firefox can't render details elements correctly in GitHub? (e.g. the triangle is not displayed in FF 49 0a2, and it doesn't collapse anything in FF mobile)

**Comment by yuku-t** [comment]
@r7kamura It seems that the triangle rendering problem is CSS issue. https://github.com/necolas/normalize.css/issues/604 may help.

Although some browsers do not implement the collapse-by-clicking-summary-behavior, it is not serious problem as long as they render whole contents. If it is worth fixed there are [some polyfills](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#details-and-summary) to do so.

**Comment by r7kamura** [comment]
I see. It looks good, if you add those supports to Qiita.

**Comment by yaotti** [comment]
@yuku-t The introduction of these tags looks good to me. :+1:

**Comment by yuku-t** [comment]
😄

**Pull request merged**
