### PR TITLE
Add timeout support to syntax highlight filter

### PR DESCRIPTION
**Pull request by uasi**
Let SyntaxHighlightFilter stop if it takes longer than `context[:syntax_highlight_timeout]` seconds.

Note that it is "soft" timeout, rather than "hard" timeout such as one provided by `Timeout::timeout`, so a filter may not stop immediately after it passes the time limit.

If anyone is curious about why we don't just use `Timeout::timeout`, here's the reason [Why Ruby’s Timeout is dangerous (and Thread.raise is terrifying) - Julia Evans](https://jvns.ca/blog/2015/11/27/why-rubys-timeout-is-dangerous-and-thread-dot-raise-is-terrifying/)

Related to https://github.com/increments/Qiita/issues/10753 (summary: Qiita's edit request renderer may fail if the request contains too many code blocks)

### CODE REVIEW

**Comment by r7kamura** [comment]
@uasi If it times out, what will happen to the entire result? In other words, is the result appropriate for users to see it?

**Comment by r7kamura** [comment]
By the way, this is a public repo, despite the link you pasted is private, so many of people can't see it.

**Comment by uasi** [comment]
@r7kamura SyntaxHighlightFilter processes each code block in the document in order of appearance, one by one. The timeout occurs only after processing a code block and before processing the next one. So, if it times out, the first few code blocks are highlighted and the rest are not. I think this is acceptable.

**Comment by uasi** [comment]
Maybe the remaining code blocks should be processed as if their language were specified as “text”, to make output DOM structure consistent. I'll take another look.

**Comment by r7kamura** [comment]
@uasi I think it must be re-rendered (e.g. by Resque) after returning response if it timed out because the result HTML is incomplete. To do this, you need to tell the result of the timeout. We have no means of knowing that at the current code.

**Comment by uasi** [comment]
@r7kamura Updated to set `result[:syntax_highlight_timed_out]`  to `true` when it times out. Also made SyntaxHighlightFilter run in a degraded mode (process every code block as text, which is considerably faster) even after timeout for the sake of consistency.

By the way, we currently have no chance to re-render the result since Qiita renders diff [on the fly without any sort of cache](https://github.com/increments/Qiita/blob/7c8b2e3c8ada3c1439c2efafcf59adde97534f3a/app/views/partials/diff/_raw_body.html.slim).

**Comment by r7kamura** [comment]
I see. It doesn't matter if syntax-highlighting is only used at the diff pages.

**Comment by r7kamura** [comment]
Looks good 👍

**Pull request merged**
