### PR TITLE
Add some attributes to a elements for hover card

### PR DESCRIPTION
**Pull request by yuku-t**
This PR adds `class="js-user-hover-card"` and `data-user-url-name` attributes to `A` elements generated by the mention filter to implement user hover card feature in Qiita core.

@r7kamura, could you review this PR?

### CODE REVIEW

**Comment by r7kamura** [comment]
@yuku-t Almost looks find, however, what do you plan to take hover-cards on `@all` and group mentions?

**Comment by bucaran** [comment]
> what do you plan to take hover-cards on @all and group mentions?

@r7kamura I think we should do nothing in this case, or at least, nothing for now.

**Comment by r7kamura** [comment]
> I think we should do nothing in this case, or at least, nothing for now.

OK, I asked just out of interest 🙆
It looks easy to detect them from data-user-url-name.

**Comment by bucaran** [comment]
So, what I mean is, we should finish the basic hovercard feature first, then we can add more features.

For example, just an idea, we can create a special hovercard with all the member profile pictures for `@all`.

**Comment by bucaran** [comment]
Thanks! So, what I mean is, we should finish the basic hovercard feature first, then we can add more features.

For example, just an idea, we can create a special hovercard with all the member profile pictures for ＠all. Good? or maybe too much?

@r7kamura @yuku-t @yoichiro What do you think?

**Comment by yuku-t** [comment]
@r7kamura 

> what do you plan to take hover-cards on `@all` and group mentions?

As @bucaran said, I plan to support hover cards for individuals first. So I didn't change [this line](https://github.com/increments/qiita-markdown/pull/36/files#diff-d27e84ceb5b5d32c6ec5a50c8fc12d0eR47), but I forgot to take group mentions into account 😅 

We should not add `data-user-url-name` for group mentions, I think. How about you?

@bucaran 

> we can create a special hovercard with all the member profile pictures for `@all`

Pretty interesting 👍

**Comment by r7kamura** [comment]
> We should not add data-user-url-name for group mentions, I think. How about you?

well, that will do it.
As an alternative idea, we can add another data attribute that tells its mention type (e.g. `data-mention-type`). In this case, we might want to use more generic name like `data-mention-target-name`.

**Comment by yuku-t** [comment]
> As an alternative idea, we can add another data attribute that tells its mention type (e.g. `data-mention-type`). In this case, we might want to use more generic name like `data-mention-target-name`.

👍 

I use `class="js-hovercard"` `data-hovercard-target-type="user"` and `data-hovercard-target-name` so that we can use these attributes for not only mention but also home page, "知り合いかも", etc.

**Comment by yuku-t** [comment]
@r7kamura do you mind if I merge this PR?

**Comment by r7kamura** [comment]
@yuku-t OK, just merged it, but I won't care about it soon because I'm on summer vacation now

**Comment by yuku-t** [comment]
😨  oops, BTW, thanks for rapid reply 😄

**Comment by bucaran** [comment]
@yuku-t Would it be possible to wrap the `<a>` element in a `<span>`? 

In the current state, the root element of the hovercard will be a link. If so, the entire hovercard will be clickable as a link.

**Pull request merged**
